---
- name: install required packages
  apt:
    name:
      - unzip
      - wget
      - xz-utils
    state: present
  become: true

- name: gather package facts
  package_facts:
    manager: "auto"

- name: fetch latest vagrant debian download link
  shell: >
    wget -qO- {{ vagrant_page }}
    | tr \" \\n | grep https\*:// | grep 64.deb
  register: vagrant_debian
  when: "'vagrant' not in ansible_facts.packages"
  notify: install vagrant
