---
- name: Verify
  hosts: all

  tasks:
    - name: Collect package facts.
      package_facts:
        manager: "auto"

    - name: Verify Vagrant is installed.
      assert:
        that:
          - "'vagrant' in ansible_facts.packages"
        success_msg: "Vagrant is installed."
        fail_msg: "Vagrant is not installed."
